"use strict";
const questions = [
  { url_image: "images/anh1.png", answer: "BÁO CÁO" },
  { url_image: "images/anh2.png", answer: "BA HOA" },
  { url_image: "images/anh3.png", answer: "CUNG CẦU" },
  { url_image: "images/anh4.png", answer: "CA DAO" },
  { url_image: "images/anh5.png", answer: "CÂN BẰNG" },
  { url_image: "images/anh6.png", answer: "MẬT MÃ" },
  { url_image: "images/anh7.png", answer: "NEO ĐƠN" },
  { url_image: "images/anh8.png", answer: "KHẨU CUNG" },
  { url_image: "images/anh9.png", answer: "GIẤY BẠC" },
  { url_image: "images/anh10.png", answer: "HOA HẬU" },
  { url_image: "images/anh11.png", answer: "HÀNG LANG" },
  { url_image: "images/anh12.png", answer: "THẢM THIẾT" },
  { url_image: "images/anh13.png", answer: "Ô BA MA" },
  { url_image: "images/anh14.png", answer: "BÓNG BẢY" },
  { url_image: "images/anh15.png", answer: "NHẬT BÁO" },
  { url_image: "images/anh16.png", answer: "DẦU CÁ" },
  { url_image: "images/anh17.png", answer: "TAY TRẮNG" },
  { url_image: "images/anh18.png", answer: "XÀ KÉP" },
  { url_image: "images/anh19.png", answer: "CHÂN THÀNH" },
  { url_image: "images/anh20.png", answer: "GẠCH HOA" },
  { url_image: "images/anh21.png", answer: "HỌC ĐƯỜNG" },
  { url_image: "images/anh22.png", answer: "XE TĂNG" },
  { url_image: "images/anh23.png", answer: "CẦU MÂY" },
  { url_image: "images/anh24.png", answer: "TÌNH TRƯỜNG" },
  { url_image: "images/anh25.png", answer: "HỨNG THÚ" },
  { url_image: "images/anh26.png", answer: "BAO HÀM" },
  { url_image: "images/anh27.png", answer: "ĐẦU GẤU" },
  { url_image: "images/anh28.png", answer: "CÁ NGỰA" },
  { url_image: "images/anh29.png", answer: "BÀI BẠC" },
  { url_image: "images/anh30.png", answer: "HỎI CUNG" },
  { url_image: "images/anh31.png", answer: "NỘI GIÁN" },
  { url_image: "images/anh32.png", answer: "ĐẦU THÚ" },
  { url_image: "images/anh33.png", answer: "LANG THANG" },
  { url_image: "images/anh34.png", answer: "CHỈ ĐIỂM" },
  { url_image: "images/anh35.png", answer: "TRANH THỦ" },
  { url_image: "images/anh36.png", answer: "ÁP ĐẢO" },
  { url_image: "images/anh37.png", answer: "BỈ ỔI" },
  { url_image: "images/anh38.png", answer: "CỔ LOA" },
  { url_image: "images/anh39.png", answer: "BẠC TÌNH" },
  { url_image: "images/anh40.png", answer: "HÀI LÒNG" },
];

